feat(en_US): add product description and pricing doc
emqx/cloud-docs pull request #110
Opened 2021-05-08 02:33 UTC by chenx-work

2021-05-08 08:44 UTC, Zhiw commented
将中文文档复制过来，然后对照翻译，配图也同样复制

2021-05-11 08:15 UTC, Zhiw requested changes

2021-05-11 08:15 UTC, Zhiw commented on en_US/README.md
> +- **Send data to HTTP services and other MQTT services**:
格式错误

2021-05-11 08:15 UTC, Zhiw commented on en_US/pricing.md
> +| Version      | Specifications                          | Base Charge     | Free Traffic  | Overage Unit Price |
按照中文来

2021-05-11 08:20 UTC, zibuyu1995 requested changes
所有 Edition 改为 Plan

2021-05-11 08:48 UTC, Zhiw commented on en_US/README.md
> +Consumer messages sent down to the device, transaction-level platform commands sent down
Consumer 是个名词

2021-05-11 09:45 UTC, closed without merging