fix(docs): fix pricing/intro docs
emqx/cloud-docs pull request #116
Opened 2021-05-11 10:06 UTC by chenx-work

2021-05-11 10:17 UTC, Zhiw approved these changes

2021-05-12 03:11 UTC, zibuyu1995 requested changes

2021-05-12 03:11 UTC, zibuyu1995 commented on en_US/pricing.md
> +- Retain the right to recover the overdraft balance
- Reserve the right to recover money owed on the account.
- Delete all deployments under your account and delete the deployment data and the data will not be recovered.

2021-05-12 03:11 UTC, zibuyu1995 commented on en_US/pricing.md
> +::: danger
英文没有透支额度

2021-05-12 05:55 UTC, zibuyu1995 approved these changes

2021-05-12 06:29 UTC, Adek06 approved these changes

2021-05-14 01:06 UTC, merged