fix(docs): add Azure stuff
emqx/cloud-docs pull request #134
Opened 2021-07-02 02:11 UTC by chenx-work

2021-07-02 10:21 UTC, Adek06 requested changes

2021-07-02 10:21 UTC, Adek06 commented on en_US/deployments/calculator.md
> +| Azure    | US East(N.Virginia) |
还有两个区域 Germany West Central,  Southeast Asia

2021-07-05 01:05 UTC, Zhiw approved these changes

2021-07-05 02:07 UTC, Adek06 requested changes

2021-07-05 02:07 UTC, Adek06 commented on en_US/deployments/calculator.md
> +| Azure    | US East(N.Virginia), Germany West (Central), Southeast Asia |
德国这里不用括号。统一改成下面这个吧。这是 Azure 官网的表示方式

![image](https://user-images.githubusercontent.com/25602645/124408358-aa6cc080-dd78-11eb-9292-00f6389e0804.png)

2021-07-05 02:48 UTC, Adek06 approved these changes

2021-07-06 01:47 UTC, zibuyu1995 approved these changes

2021-07-06 01:47 UTC, merged