feat(rule_engine):add doc of rule engine events
emqx/cloud-docs pull request #137
Opened 2021-07-06 10:01 UTC by wuzufeng

2021-07-06 13:17 UTC, Zhiw reviewed
虽然 emqx 文档也是这么写，但是对于消息`目的用户名`和`消息目的 Client ID`还是会有点困惑

2021-07-06 13:17 UTC, Zhiw commented on zh_CN/rule_engine/rule_engine_events.md
> +# 新增事件订阅
标题应该是事件主题吧

2021-07-06 13:17 UTC, Zhiw commented on zh_CN/rule_engine/rule_engine_events.md
> +本文将从 设备上下线通知，设备消息通知和设备主题订阅通知三个方面分别介绍新增事件订阅主题使用和各个字段的含义。
从后面多了一个空格

2021-07-06 13:17 UTC, Zhiw commented on zh_CN/rule_engine/rule_engine_events.md
> +设备上线的消息主题为 `$events/client_connected`，在规则面板中点击创建规则，然后输入如下规则匹配 SQL 语句便可完成设备上线规则的创建，当新设备上线并连接到EMQ X Cloud便会触发该规则。
中英文之间加空格，下同

2021-07-06 16:38 UTC, zibuyu1995 requested changes

2021-07-06 16:38 UTC, zibuyu1995 commented on zh_CN/rule_engine/rule_engine_events.md
> +# 新增事件订阅
参考 azure 先叫事件订阅

2021-07-06 16:38 UTC, zibuyu1995 commented on zh_CN/rule_engine/rule_engine_events.md
> +本文将从 设备上下线通知，设备消息通知和设备主题订阅通知三个方面分别介绍新增事件订阅主题使用和各个字段的含义。
设备上下线、消息通知和主题订阅通知，三个方面分别介绍新增事件订阅主题使用和各个字段的含义。

2021-07-06 16:38 UTC, zibuyu1995 commented on zh_CN/rule_engine/rule_engine_events.md
> +| clientid | 消息目的 Client ID |
客户端ID

2021-07-06 16:38 UTC, zibuyu1995 commented on zh_CN/rule_engine/rule_engine_events.md
> +| username | 消息目的用户名 |
用户名

2021-07-06 16:38 UTC, zibuyu1995 commented on zh_CN/rule_engine/rule_engine_events.md
> +| username | 消息目的用户名 |
同上

2021-07-07 01:58 UTC, zibuyu1995 approved these changes

2021-07-07 03:01 UTC, Zhiw reviewed
在 `directory.json` 中添加引用，否则不会出现在左侧目录中

2021-07-07 03:01 UTC, Zhiw commented on zh_CN/rule_engine/rule_engine_events.md
> +
去掉`新增`

2021-07-07 03:21 UTC, Zhiw approved these changes

2021-07-09 06:50 UTC, merged