feat(docs): add docs of authentication management with client
emqx/cloud-docs pull request #162
Opened 2021-11-08 05:51 UTC by wuzufeng

2021-11-08 10:05 UTC, zibuyu1995 requested changes

2021-11-08 10:05 UTC, zibuyu1995 commented on zh_CN/deployments/logs.md
> +| 日志                                                                                                               | 级别     | 原因                                                   | 处理
这里是不是可以不用表格，用子标题？表格会影响展示，原因字数一多不好看

2021-11-08 10:05 UTC, zibuyu1995 commented on zh_CN/deployments/alerts.md
> +| 规则引擎 MySQL 资源异常      | error   | 部署规则引擎 MySQL 资源异常                               | 检查部署规则引擎中 MySQL 资源                       |
cloud 没有详细资源异常，只有资源 ID，可以看看 backend/app/utils/alerts.py

2021-11-08 10:05 UTC, zibuyu1995 commented on zh_CN/deployments/alerts.md
> +| 部署 QoS 1 消息丢弃告警      | warning | 部署由于客户端长期离线或主题未被订阅导致大量 QoS 1 消息丢弃    | 检查发布消息的主题是否有被订阅和订阅的客户端是否在线     |
常规发出去的告警只有消息丢弃，客户端长期离线并设置 clean session 为 False 导致，解决：客户端设置 clean session 为 False 或客户端设置自动重连。下面日志也是一样

2021-11-08 10:05 UTC, zibuyu1995 commented on zh_CN/deployments/alerts.md
> +| 连接数过高                 | warning  | 部署连接数过高：{当前连接数}                              | 升级部署规格                                      |
这里弄成 子标题会不会更好一点？

2021-11-08 10:05 UTC, zibuyu1995 commented on en_US/deployments/logs.md
> +
这里留给陈来翻译，你先把中文文档修改

2021-11-08 10:05 UTC, zibuyu1995 commented on en_US/deployments/alerts.md
> +| Type                            | Level   | Information                                                                                    | Solution
这里也是，留给陈来翻译一下

2021-11-09 02:46 UTC, wuzufeng commented
@zibuyu1995 常见日志分析已修改为子标题，其他问题已修改，英文的 log 文档的日志分析改动比较大就先删掉，等陈先滢翻译吧

2021-11-09 03:34 UTC, zibuyu1995 commented on zh_CN/deployments/alerts.md
> +| 部署 QoS 1 消息丢弃告警      | warning | 部署由于客户端长期离线或主题未被订阅导致大量 QoS 1 消息丢弃    | 检查发布消息的主题是否有被订阅和订阅的客户端是否在线     |
这里告警没改

2021-11-09 03:34 UTC, zibuyu1995 commented on zh_CN/deployments/alerts.md
> +| 规则引擎 MySQL 资源异常      | error   | 部署规则引擎 MySQL 资源异常                               | 检查部署规则引擎中 MySQL 资源                       |
@wuzufeng 这里没改

2021-11-09 03:40 UTC, wuzufeng commented on zh_CN/deployments/alerts.md
> +| 规则引擎 MySQL 资源异常      | error   | 部署规则引擎 MySQL 资源异常                               | 检查部署规则引擎中 MySQL 资源                       |
@zibuyu1995 已添加修改

2021-11-09 06:46 UTC, Zhiw approved these changes

2021-11-09 07:33 UTC, zibuyu1995 requested changes

2021-11-09 07:33 UTC, zibuyu1995 commented on zh_CN/deployments/alerts.md
> +| 部署 QoS 1 消息丢弃告警      | warning | 部署由于客户端长期离线或主题未被订阅导致大量 QoS 1 消息丢弃    | 客户端设置 clean session 为 False 或客户端设置自动重连 |
部署 QoS 1 消息丢弃告警 改为部署消息丢弃

2021-11-09 07:46 UTC, wuzufeng commented on zh_CN/deployments/alerts.md
> +| 部署 QoS 1 消息丢弃告警      | warning | 部署由于客户端长期离线或主题未被订阅导致大量 QoS 1 消息丢弃    | 客户端设置 clean session 为 False 或客户端设置自动重连 |
@zibuyu1995 logs 和 alerts 文档均已修改

2021-11-10 01:47 UTC, zibuyu1995 approved these changes

2021-11-10 05:43 UTC, Adek06 approved these changes

2021-11-10 05:44 UTC, merged