User manage
emqx/cloud-docs pull request #163
Opened 2021-11-11 05:57 UTC by azuregaya

User management & Project Center Documents

2021-11-12 02:03 UTC, Adek06 commented on zh_CN/deployments/project_center.md
> +项目中心提供了一个企业中多个组织或者部门独立使用和管理MQTT集群的能力，可以分配不同的角色对平台的各项能力进行更加精细化的管理。基于项目中心，每个组织或者部门可以单独管理自己的MQTT集群，并可以独立核算。在多项目的机制下，部署需建立在项目下面，并且一个部署只能属于一个项目。
英文和中文用空格隔开

2021-11-12 02:07 UTC, Adek06 requested changes

2021-11-12 02:07 UTC, Adek06 commented on zh_CN/deployments/project_center.md
> +3. 再确认列表中可以再次修改账号的角色或删除账号的授权。点击确认。这样就完成了一个项目的创建。
`授权。点击确认` -> `授权，点击确认`

2021-11-12 02:07 UTC, Adek06 commented on zh_CN/users/intro.md
> +子账号是由EMQ X Cloud用户自己在平台上创建的账号，子账号也需要通过邮箱认证之后激活。同样一个邮箱即可以注册成一个EMQ X Cloud平台账号，也可以同时成为其他平台账号的子账号，通过不同的登录界面以登录不同的账号体系。
中英用空格隔开

2021-11-12 02:29 UTC, Zhiw commented on zh_CN/deployments/project_center.md
> +点击右上角`新建项目`钮开始新建，新建项目分为三个步骤：
按钮

2021-11-12 02:29 UTC, Zhiw commented on zh_CN/deployments/project_center.md
> +> 取消账号全部的角色等同于删除改账号的项目授权。
改账号 -> 该账号

2021-11-12 02:29 UTC, Zhiw commented on zh_CN/users/intro.md
> +**项目管理员**:拥有查看修改项目的权限和修改删除部署的权限。项目管理员主要用于项目部署相关管理，比如一个组织或者部门需要单独拥有
冒号，全角

2021-11-15 02:12 UTC, Zhiw commented on zh_CN/deployments/project_center.md
> +3. 再确认列表中可以再次修该账号的角色或删除账号的授权，点击确认。这样就完成了一个项目的创建。
修该 -> 修改

2021-11-16 09:02 UTC, zibuyu1995 requested changes

2021-11-16 09:02 UTC, zibuyu1995 commented on zh_CN/users/user.md
> +	* 填写邀请人的邮箱
填写被邀请人的邮箱

2021-11-16 09:02 UTC, zibuyu1995 commented on zh_CN/users/user.md
> +2. 登录邮箱，接收邀请邮件，并通过链接来验证并激活账号。需要注意的是，邀请邮件中有两个地址，一个是第一次激活并登录的，另一个为常用的登录地址，用于之后的登录。子账号的密码请由开通账号的管理员发放（或找管理员获得）。
登录被邀请者邮箱

2021-11-16 09:02 UTC, zibuyu1995 commented on zh_CN/users/user.md
> +
多余的行可以删除吧

2021-11-17 08:38 UTC, Zhiw approved these changes

2021-11-17 08:43 UTC, 0721Betty approved these changes

2021-11-17 09:40 UTC, wuzufeng requested changes

2021-11-17 09:40 UTC, wuzufeng commented on zh_CN/users/user.md
> +
@azuregaya 这里没有删除干净 60-70行都是空白

2021-11-18 12:31 UTC, zibuyu1995 approved these changes

2021-11-18 12:31 UTC, merged