feat(docs): add python sdk connect to deployments docs
emqx/cloud-docs pull request #165
Opened 2021-12-01 09:39 UTC by wuzufeng

2021-12-01 10:00 UTC, Adek06 commented on zh_CN/connect_to_deployments/python_sdk.md
> +已经创建了部署，在部署概览下可以查看到连接相关的信息，同时你可以了使用WebSocket先测试连接到MQTT服务器。
中英文间空隔

2021-12-01 10:07 UTC, Adek06 commented on zh_CN/connect_to_deployments/python_sdk.md
> +## 安装使用客户端
`安装使用客户端` 改成 `安装 MQTT 客户端` 好点吧

2021-12-01 10:11 UTC, wuzufeng commented on zh_CN/connect_to_deployments/python_sdk.md
> +## 安装使用客户端
@azuregaya 这个是李研模板上的，需要修改吗

2021-12-01 10:11 UTC, Adek06 commented on zh_CN/connect_to_deployments/python_sdk.md
> +以上为您演示了如何使用paho.mqtt.m2mqtt 客户端库连接到EMQ X Cloud，可以在 [这里](https://github.com/emqx/MQTT-Client-Examples/tree/master/mqtt-client-Python3/) 下载到示例的源码。
中英文间空隔

2021-12-01 10:14 UTC, Adek06 commented on zh_CN/connect_to_deployments/python_sdk.md
> +同时也可以在 [GitHub](https://github.com/emqx/MQTT-Client-Examples) 上找到更多起他语言的 Demo 示例。
`起他` -> `其它`

2021-12-02 02:51 UTC, Adek06 commented on zh_CN/connect_to_deployments/python_sdk.md
> +已经创建了部署，在部署概览下可以查看到连接相关的信息，同时你可以了使用 WebSocket 先测试连接到 MQTT 服务器。
`同时你可以了使用`

多了一个了

2021-12-02 08:25 UTC, Zhiw commented on zh_CN/connect_to_deployments/python_sdk.md
> +以上为您演示了如何使用 paho.mqtt.m2mqtt 客户端库连接到 EMQ X Cloud，可以在 [这里](https://github.com/emqx/MQTT-Client-Examples/tree/master/mqtt-client-Python3/) 下载到示例的源码。
这里没改 paho.mqtt.m2mqtt

2021-12-02 09:11 UTC, zibuyu1995 requested changes

2021-12-02 09:11 UTC, zibuyu1995 commented on zh_CN/connect_to_deployments/python_sdk.md
> +    client.connect(broker, port)
看一下 clean session 默认是否为 Ture，不为 True 需要设置为 True

2021-12-03 02:02 UTC, zibuyu1995 approved these changes

2021-12-03 06:05 UTC, azuregaya commented on zh_CN/connect_to_deployments/python_sdk.md
> +## 安装使用客户端
可以改成 `安装 MQTT 客户端`

2021-12-03 06:19 UTC, wuzufeng commented on zh_CN/connect_to_deployments/python_sdk.md
> +## 安装使用客户端
@Adek06 @azuregaya 已修改

2021-12-03 06:35 UTC, azuregaya commented on en_US/connect_to_deployments/python_sdk.md
> +This project uses Python 3.8 to develop and test. Readers can use the following command to confirm the Python version.
This project uses Python 3.8 to develop and test. Confirm the Python version by the following command.

2021-12-03 06:35 UTC, azuregaya commented on en_US/connect_to_deployments/python_sdk.md
> +Please find the address and port information in the Deployment Overview.
address -> host

2021-12-03 06:35 UTC, azuregaya commented on en_US/connect_to_deployments/python_sdk.md
> +Set the address, port and topic of MQTT Broker connection. At the same time, we call the Python function 'random.randint' to randomly generate the MQTT client id.
address -> host

2021-12-03 06:35 UTC, azuregaya commented on en_US/connect_to_deployments/python_sdk.md
> +Run the code of publishing messages, we will see that the client connects successfully and publishes messages successfully
Run the code of publishing messages, we will see that the client connects and publishes messages successfully.

2021-12-03 06:35 UTC, azuregaya commented on en_US/connect_to_deployments/python_sdk.md
> +This shows you how to use the paho-mqtt client library to connect to the EMQ X Cloud.
All of the above shows that how to use the paho-mqtt client library to connect to the EMQ X Cloud.

2021-12-03 06:52 UTC, wuzufeng commented on en_US/connect_to_deployments/python_sdk.md
> +This shows you how to use the paho-mqtt client library to connect to the EMQ X Cloud.
@azuregaya 已修改

2021-12-03 07:30 UTC, Zhiw approved these changes

2021-12-07 02:11 UTC, merged