doc(api.md): add api doc
emqx/cloud-docs pull request #17
Opened 2020-09-11 06:00 UTC by oucb

2020-09-11 06:11 UTC, Adek06 commented
这 api.md 怎么是空的

2020-09-11 06:20 UTC, Adek06 commented
开头加个目录，或者拆开写。现在这样不方便查询

2020-09-11 06:21 UTC, Adek06 commented on zh_CN/api.md
> +###
这里有个空的标题

2020-09-11 06:58 UTC, Zhiw reviewed
建议加上一个简单的如何使用API 的说明，包含URL构成，认证

2020-09-11 06:58 UTC, Zhiw commented on zh_CN/api.md
> +>  GET /api/brokers/{node}
API 地址已经包含/api，所以此处不再加这个path

2020-09-11 07:27 UTC, oucb commented on zh_CN/api.md
> +>  GET /api/brokers/{node}
这里带 `/api` 前缀只是为了更直观表示这是一个 `api` ，没有表达出直接和 API 地址拼接在一起去调用的意思，不合适的话我把这个前缀去掉

2020-09-11 07:37 UTC, oucb commented on zh_CN/api.md
> +###
@Adek06 已调整

2020-09-11 07:43 UTC, zibuyu1995 requested changes

2020-09-11 07:43 UTC, zibuyu1995 commented on zh_CN/api.md
> +
这里放张图

2020-09-11 07:43 UTC, zibuyu1995 commented on zh_CN/api.md
> +
### API 地址
您可以在部署详情页面下的 API 访问中，获取到 API 访问地址
图片

2020-09-11 07:43 UTC, zibuyu1995 commented on zh_CN/api.md
> +>  GET /api/brokers/{node}
移除 /api

2020-09-14 01:41 UTC, Zhiw approved these changes

2020-09-14 01:47 UTC, Adek06 approved these changes

2020-09-14 06:37 UTC, merged