docs(messages): add document of messages
emqx/cloud-docs pull request #18
Opened 2020-09-11 06:13 UTC by Adek06

2020-09-11 06:16 UTC, oucb approved these changes

2020-09-11 07:03 UTC, Zhiw reviewed
统一检查一下空格问题

2020-09-11 07:03 UTC, Zhiw commented on zh_CN/deployments/rule_engine.md
> +EMQ X Rule Engine (以下简称规则引擎) 用于配置 EMQ X 消息流与设备事件的处理、响应规则。规则引擎不仅提供了清晰、灵活的 "配置式" 的业务集成方案，简化了业务开发流程，提升用户易用性，降低业务系统与 EMQ X 的耦合度；也为 EMQ X 的私有功能定制提供了一个更优秀的基础架构。
`配置式`两边的空格

2020-09-11 07:03 UTC, Zhiw commented on zh_CN/deployments/rule_engine.md
> +规则描述了 数据从哪里来、如何筛选并处理数据、处理结果到哪里去 三个配置，即一条可用的规则包含三个要素：
空格

2020-09-11 07:03 UTC, Zhiw commented on zh_CN/deployments/rule_engine.md
> +触发事件：规则通过事件触发，触发时事件给规则注入事件的上下文信息（数据源），通过 SQL 的 FROM 子句指定事件类型；
三个要素应该是list格式吧

2020-09-11 07:03 UTC, Zhiw commented on zh_CN/messages/README.md
> +用户也可以通过订阅相关主题的方式来实现类似的功能，但是在 EMQ X CLOUD 中内置了对这些持久化的支持；相比于前者，后者的执行效率更高，也能大大降低开发者的工作量。
CLOUD -> Cloud

2020-09-11 07:53 UTC, Adek06 commented
mac 上无法输出全角双引号，要么用直角引号，要么就只能 空格 + 引号。

直角引号好像输出更友好一些
https://www.zhihu.com/question/268360833/answer/337876325

2020-09-11 08:21 UTC, zibuyu1995 requested changes

2020-09-11 08:21 UTC, zibuyu1995 commented on zh_CN/messages/README.md
> +用户也可以通过订阅相关主题的方式来实现类似的功能，但是在 EMQ X Cloud 中内置了对这些持久化的支持；相比于前者，后者的执行效率更高，也能大大降低开发者的工作量。
简介太少，就把使用限制放在这里

2020-09-11 08:21 UTC, zibuyu1995 commented on zh_CN/messages/README.md
> +用户也可以通过订阅相关主题的方式来实现类似的功能，但是在 EMQ X Cloud 中内置了对这些持久化的支持；相比于前者，后者的执行效率更高，也能大大降低开发者的工作量。
## 使用限制
* 对于免费试用部署以及共享部署：数据库等资源访问仅支持公网访问，因此在创建资源前您需要确保资源具有公网访问能力，同时开放安全组。

* 对于正式部署:  数据库等资源访问仅支持内网访问，因此在创建资源前您需要先配置 VPC 对等连接，同时开放安全组。

2020-09-11 10:03 UTC, zibuyu1995 approved these changes

2020-09-11 10:06 UTC, zibuyu1995 requested changes

2020-09-11 10:06 UTC, zibuyu1995 commented on zh_CN/messages/README.md
> +EMQ X Cloud 的消息存储功能依赖于规则引擎。如果你事先未了解过何为规则引擎，可以参考指南——[规则引擎](../deployments/rule_engine.md)。
把这句话放在简介里面去

2020-09-11 10:06 UTC, zibuyu1995 commented on zh_CN/messages/README.md
> +EMQ X Cloud 的消息存储功能依赖于规则引擎。如果你事先未了解过何为规则引擎，可以参考指南——[规则引擎](../deployments/rule_engine.md)。
使用限制：
为保证您能正常使用 EMQ X Cloud 消息存储，因此EMQ X Cloud 有如下限制:

2020-09-14 01:27 UTC, Adek06 commented on zh_CN/messages/README.md
> +用户也可以通过订阅相关主题的方式来实现类似的功能，但是在 EMQ X Cloud 中内置了对这些持久化的支持；相比于前者，后者的执行效率更高，也能大大降低开发者的工作量。
@zibuyu1995

2020-09-14 01:34 UTC, zibuyu1995 approved these changes

2020-09-14 01:42 UTC, Zhiw approved these changes

2020-09-14 01:43 UTC, merged