feat(doc): add valued added service docs
emqx/cloud-docs pull request #196
Opened 2022-02-14 07:07 UTC by wuzufeng

2022-02-14 09:39 UTC, 0721Betty commented on zh_CN/vas/vas-intro.md
> +增值服务是由 EMQ X Cloud 提供和运维的高可用服务计划，为了满足用户在技术和产品上的特殊需求。
EMQX Cloud

2022-02-14 09:39 UTC, 0721Betty commented on zh_CN/vas/vas-intro.md
> +EMQ X Cloud 提供的所有增值服务可以在顶部菜单栏 - `增值服务` 中找到，您可以在这里查看并开通服务。已经购买的服务会显示在我的服务中。一般情况下，我们会提供一段时间的免费试用，让您充分了解功能特性之后再决定是否购买。
EMQX Cloud

2022-02-14 09:39 UTC, 0721Betty commented on zh_CN/vas/vas-price.md
> +试用结束后会按照 **0.6 元 / 小时** 计费，会在您EMQ X Cloud的主账号下的账户余额中按小时结算扣取费用。如果账户余额不足会自动删除该增值服务。
EMQX Cloud

2022-02-14 09:39 UTC, 0721Betty commented on zh_CN/vas/vas-price.md
> +试用结束后会按照 **0.1 元 / 小时** 计费，会在您EMQ X Cloud的主账号下的账户余额中按小时结算扣取费用。如果账户余额不足会自动删除该增值服务。
EMQX Cloud

2022-02-14 09:41 UTC, 0721Betty commented on zh_CN/vas/vas-price.md
> +试用结束后会按照 **0.1 元 / 小时** 计费，会在您EMQ X Cloud的主账号下的账户余额中按小时结算扣取费用。如果账户余额不足会自动删除该增值服务。
且英文左右空格

2022-02-15 05:55 UTC, Zhiw commented on zh_CN/vas/intranet_lb.md
> +# 内网负载均衡
为什么会有两份文件

2022-02-15 06:07 UTC, Adek06 commented on zh_CN/vas/nat_gateway.md
> +# NAT 网关
这 NAT 也有两份

2022-02-15 06:09 UTC, Adek06 commented on zh_CN/vas/vas-price.md
> +NAT网关开通之后会自动获得14天免费试用，在第一个试用实例结束或删除后，下一个创建的实例将收取费用。
NAT 网关

中英文间加空格

2022-02-15 06:16 UTC, wuzufeng commented on zh_CN/vas/intranet_lb.md
> +# 内网负载均衡
@azuregaya 好像是合并了一个老的分支导致 intranet-lb 和intranet_lb 都存在了

2022-02-15 06:20 UTC, wuzufeng commented on zh_CN/vas/intranet_lb.md
> +# 内网负载均衡
@azuregaya 现在改的有点乱了 我来改吧

2022-02-15 06:33 UTC, wuzufeng commented on zh_CN/vas/vas-price.md
> +NAT网关开通之后会自动获得14天免费试用，在第一个试用实例结束或删除后，下一个创建的实例将收取费用。
@Adek06 @Zhiw @0721Betty 重新整理了下

2022-02-15 08:12 UTC, Zhiw commented on zh_CN/vas/vas-intro.md
> +一些增值服务是和您购买的部署关联的，在购买专业版或者标准版部署之后，才可以开通相关的增值服务，请留意服务的相关说明。如果您购买了多个版本，请选择您需要创建服务实例的部署。
标准版部署是？

2022-02-15 08:12 UTC, Zhiw commented on zh_CN/vas/vas-intro.md
> +开通完成之后，可以查看服务列表，这里将显示您所购买的同类型的所有增值服务。或者您也可以直接前往查看在部署下的增值服务。
文字与图片之间考虑增加换行，目前看起来有点挤

2022-02-15 08:12 UTC, Zhiw commented on zh_CN/vas/nat-gateway.md
> +NAT网关可以提供网络地址转换服务，为专业版部署提供访问公网资源的能力，无需 VPC 对等连接。
NAT 后空格

2022-02-15 08:22 UTC, zibuyu1995 requested changes

2022-02-15 08:22 UTC, zibuyu1995 commented on zh_CN/vas/vas-intro.md
> +一些增值服务是和您购买的部署关联的，在购买专业版或者标准版部署之后，才可以开通相关的增值服务，请留意服务的相关说明。如果您购买了多个版本，请选择您需要创建服务实例的部署。
中文还是基础版，英文改为 Standard

2022-02-15 08:44 UTC, wuzufeng commented on zh_CN/vas/nat-gateway.md
> +NAT网关可以提供网络地址转换服务，为专业版部署提供访问公网资源的能力，无需 VPC 对等连接。
@Zhiw @zibuyu1995 已修改

2022-02-16 00:45 UTC, Zhiw approved these changes

2022-02-16 01:36 UTC, Adek06 approved these changes

2022-02-16 03:09 UTC, azuregaya approved these changes

2022-02-16 03:36 UTC, 0721Betty approved these changes

2022-02-17 08:13 UTC, merged