docs(dashboard): add docs of dashboard
emqx/cloud-docs pull request #20
Opened 2020-09-14 07:20 UTC by Adek06

2020-09-14 09:32 UTC, zibuyu1995 requested changes

2020-09-14 09:32 UTC, zibuyu1995 commented on zh_CN/deployments/dashboard/README.md
> +
所有称呼 你 改为 您

2020-09-14 09:32 UTC, zibuyu1995 commented on zh_CN/deployments/dashboard/README.md
> +
点击页面中 EMQ X Dashboard 按钮，

2020-09-14 09:41 UTC, Zhiw approved these changes

2020-09-15 01:24 UTC, oucb approved these changes

2020-09-15 01:41 UTC, oucb commented on zh_CN/messages/README.md
> +EMQ X Cloud 的消息存储功能依赖于规则引擎。如果您事先未了解过何为规则引擎，可以参考指南——[规则引擎](../deployments/rule_engine.md)。
这里是不是链接到 emqx 的规则引擎介绍文档地址。图片现在是放到跟当前文档同级的 `_assets` 目录下吗

2020-09-15 02:03 UTC, zibuyu1995 approved these changes

2020-09-15 02:03 UTC, merged