refactor(data_integration): refactor doc of webhook and aliyun mongo
emqx/cloud-docs pull request #221
Opened 2022-03-11 09:03 UTC by Adek06

2022-03-11 09:08 UTC, zibuyu1995 requested changes

2022-03-11 09:31 UTC, Adek06 commented on zh_CN/rule_engine/rule_engine_aliyun_mongodb.md
>  在本文中我们将模拟温湿度数据并通过 MQTT 协议上报到 EMQX Cloud，然后使用 EMQX Cloud 规则引擎将数据转存到阿里云 MongoDB。
已修改

2022-03-11 09:34 UTC, Zhiw commented on zh_CN/rule_engine/rule_engine_aliyun_mongodb.md
> +4. 查看资源详情
要空一行，统一看一下

2022-03-11 11:44 UTC, Zhiw approved these changes

2022-03-14 02:43 UTC, wuzufeng approved these changes

2022-03-14 09:37 UTC, zibuyu1995 approved these changes

2022-03-14 09:37 UTC, merged