docs(dev_guide.md): add doc of development guide
emqx/cloud-docs pull request #23
Opened 2020-09-16 05:44 UTC by oucb

2020-09-16 06:00 UTC, Zhiw commented on zh_CN/api.md
> +**Query String Parameters:**
中文文档

2020-09-16 06:12 UTC, oucb commented on zh_CN/api.md
> +**Query String Parameters:**
这里是参考 emqx 的文档，api 文档里的全改成中文？

2020-09-16 08:41 UTC, oucb commented on zh_CN/api.md
> +**Query String Parameters:**
@Zhiw 已更改

2020-09-16 09:16 UTC, Zhiw approved these changes

2020-09-16 09:19 UTC, Adek06 approved these changes

2020-09-17 07:57 UTC, zibuyu1995 requested changes

2020-09-17 07:57 UTC, zibuyu1995 commented on zh_CN/dev_guide.md
> +集成细节以及其他集成功能需求请向 EMQ X Cloud 客服咨询。
集成细节以及其他集成功能需求您可以提工单或发送[邮件](cloud@emqx.io) 咨询

2020-09-17 08:07 UTC, oucb commented on zh_CN/dev_guide.md
> +集成细节以及其他集成功能需求请向 EMQ X Cloud 客服咨询。
@zibuyu1995 已改

2020-09-18 01:34 UTC, merged