feat(docs): add codec to vas
emqx/cloud-docs pull request #248
Opened 2022-04-19 09:56 UTC by luoyq0629

2022-04-20 01:41 UTC, Zhiw commented on zh_CN/vas/codec.md
> +2、在自定义函数 - 新建函数页面，依次填写 topic 、JavaScript 脚本，选择数据类型。
这里代码格式调一下，你可以通过预览调整
然后 topic 和 payload 的介绍可以相对再详细一点
topic：保留
payload，加上数据类型示例：Byte: [0x00,0x01]，JSON: 转换后的 JSON，字符串：原始字符串

2022-04-20 01:41 UTC, Zhiw commented on zh_CN/vas/codec.md
> +   ```payload
json

2022-04-20 01:42 UTC, zibuyu1995 requested changes

2022-04-20 01:42 UTC, zibuyu1995 commented on zh_CN/vas/codec.md
> +## 服务使用
@Zhiw 应该还要新增一个警告或者提示，告知客户不应该在函数中出现死循环或者其他一些异常情况，并且告知函数不支持比如 io 等操作，这部分警告内容可以让 addon 团队协助提供。

2022-04-20 08:55 UTC, Zhiw approved these changes

2022-04-21 01:35 UTC, shenping2021 commented on zh_CN/vas/codec.md
> +   方式一：登陆 EMQX Cloud 控制台，在顶部菜单栏点击`增值服务`，找到自定义函数，点击`开通服务`。
这里所谓的两种方式只是两个入口，目前的开通方式应该是 用户提交开通服务的工单申请后，由emqx 管理员后台开通，这里是否需要修改一下？

2022-04-21 03:02 UTC, luoyq0629 commented on zh_CN/vas/codec.md
> +   方式一：登陆 EMQX Cloud 控制台，在顶部菜单栏点击`增值服务`，找到自定义函数，点击`开通服务`。
服务开通第 3 步有关于工单流程的说明，前后都加稍微有点重复了。

2022-04-21 06:22 UTC, azuregaya commented on zh_CN/vas/codec.md
> +EMQX Cloud 的自定义函数提供了自定义 topic 数据解析的功能，即设备通过自定义 topic 上报数据，平台接收数据后，将调用用户在平台提交的数据解析脚本对设备上报的数据进行处理。
这边的的自定义 topic 是否可以就是topic？ 因为我们不像其他物联网平台有系统默认的topic，和自定义的topic，我们所有的 topic都是用户自己定的

2022-04-21 06:26 UTC, azuregaya commented on zh_CN/vas/codec.md
> +
目前 自定义函数支持 ECMAScript5.1 版本的Javascript，尚未支持 ECMAScript6 级以上版本

2022-04-21 06:32 UTC, azuregaya approved these changes

2022-04-21 06:34 UTC, luoyq0629 commented on zh_CN/vas/codec.md
> +EMQX Cloud 的自定义函数提供了自定义 topic 数据解析的功能，即设备通过自定义 topic 上报数据，平台接收数据后，将调用用户在平台提交的数据解析脚本对设备上报的数据进行处理。
已修改

2022-04-21 07:07 UTC, luoyq0629 commented on zh_CN/vas/codec.md
> +
已修改

2022-04-24 08:03 UTC, zibuyu1995 approved these changes

2022-04-24 08:03 UTC, merged