feat(docs): add api of shadow service
emqx/cloud-docs pull request #306
Opened 2022-08-16 10:31 UTC by luoyq0629

2022-08-17 02:21 UTC, azuregaya commented on zh_CN/shadow_service/invoke.md
> +## [API 通信](https://docs.emqx.com/zh/cloud/latest/api/shadow_service.html)
这里是不是该用相对路径，这个链接会不会新开窗口？

2022-08-17 02:22 UTC, azuregaya approved these changes

2022-08-17 02:31 UTC, luoyq0629 commented on zh_CN/shadow_service/invoke.md
> +## [API 通信](https://docs.emqx.com/zh/cloud/latest/api/shadow_service.html)
已修改

2022-08-17 06:59 UTC, zibuyu1995 requested changes

2022-08-17 06:59 UTC, zibuyu1995 commented on zh_CN/api/shadow_service.md
> +  "createAt": 1660618831979,
加字段说明，version 是什么意思，什么情况下会增加，create At 和 lastTime 是什么意思，并且是 UTC 时间

2022-08-17 07:52 UTC, luoyq0629 commented on zh_CN/api/shadow_service.md
> +  "createAt": 1660618831979,
已添加

2022-08-17 08:00 UTC, wuzufeng commented on zh_CN/api/shadow_service.md
> +| data[].specs | String | 规格     |
这里数据类型和下面不一样

2022-08-17 08:00 UTC, wuzufeng commented on zh_CN/api/shadow_service.md
> +| data[].power | String | 电量     |
这里数据类型和下面不一样

2022-08-17 08:59 UTC, luoyq0629 commented on zh_CN/api/shadow_service.md
> +| createdAt | Integer | JSON 创建时间（UTC） |
已修改

2022-08-17 09:00 UTC, luoyq0629 commented on zh_CN/api/shadow_service.md
> +| version   | String  | JSON 修改的版本号    |
已修改

2022-08-17 09:02 UTC, luoyq0629 commented on zh_CN/api/shadow_service.md
> +| data[].specs | String | 规格     |
已修改

2022-08-17 09:02 UTC, luoyq0629 commented on zh_CN/api/shadow_service.md
> +| data[].power | String | 电量     |
已修改

2022-08-17 09:30 UTC, wuzufeng approved these changes

2022-08-18 01:57 UTC, zibuyu1995 approved these changes

2022-08-18 01:57 UTC, merged