feat(docs): add clickhouse_cloud to data_integrations
emqx/cloud-docs pull request #325
Opened 2022-10-19 09:28 UTC by luoyq0629

2022-10-19 13:30 UTC, zibuyu1995 approved these changes

2022-10-20 01:36 UTC, azuregaya approved these changes

2022-10-20 02:01 UTC, chenx-work approved these changes

2022-11-01 17:00 UTC, lucas-emqx commented on en_US/rule_engine/rule_engine_save_clickhouse_cloud.md
> +ClickHouse provides a [quick start](https://clickhouse_cloud.com/docs/en/quick-start), just follow the steps on the doc and you will get an instance up and running in minutes. During this setup, Iwe
"During this setup, **Iwe** deployed"

2022-11-01 17:01 UTC, lucas-emqx commented on en_US/rule_engine/rule_engine_save_clickhouse_cloud.md
> +The credentials you created is also needed for the integration.
"created is also" -> "created are also"

2022-11-01 17:03 UTC, lucas-emqx requested changes
added a couple of comments for `en_US/rule_engine/rule_engine_save_clickhouse_cloud.md`

2022-11-02 14:37 UTC, lucas-emqx approved these changes

2022-11-03 03:28 UTC, merged