feat(docs): add mongo_atlas to data_integrations and fix errors
emqx/cloud-docs pull request #331
Opened 2022-11-08 06:08 UTC by luoyq0629

2022-11-08 08:51 UTC, azuregaya approved these changes

2022-11-08 13:14 UTC, chenx-work approved these changes

2022-11-08 23:51 UTC, lucas-emqx requested changes

2022-11-08 23:51 UTC, lucas-emqx commented on en_US/rule_engine/rule_engine_save_mongodb_atlas.md
> +   Check the rule monitoring and add one to the number of success.
the "Success" number.

or

the number of successes.

2022-11-14 05:16 UTC, lucas-emqx approved these changes

2022-11-14 08:28 UTC, merged