Added guide to Data Integration with RDS for MySQL
emqx/cloud-docs pull request #333
Opened 2022-11-14 15:43 UTC by lucas-emqx

2022-11-15 07:08 UTC, zibuyu1995 requested changes

2022-11-15 07:08 UTC, zibuyu1995 commented on en_US/rule_engine/rule_engine_save_rds_mysql.md
> +  - Start at the second step ("Create Rule") of "Data Integrations Configuration"
Can you add a test step? Something like this https://docs.emqx.com/en/cloud/latest/rule_engine/rule_engine_save_mysql.html#test

2022-11-15 07:08 UTC, zibuyu1995 commented on en_US/rule_engine/rule_engine_save_rds_mysql.md
> +- Follow the "Data Integrations Configuration" and "Test" section of [this EMQX tutorial](https://docs.emqx.com/en/cloud/latest/rule_engine/rule_engine_save_mysql.html#data-integrations-configuration
Can you provide example SQL for the rule?

2022-11-17 06:49 UTC, lucas-emqx commented on en_US/rule_engine/rule_engine_save_rds_mysql.md
> +  - Start at the second step ("Create Rule") of "Data Integrations Configuration"
done!

2022-11-17 06:49 UTC, lucas-emqx commented on en_US/rule_engine/rule_engine_save_rds_mysql.md
> +- Follow the "Data Integrations Configuration" and "Test" section of [this EMQX tutorial](https://docs.emqx.com/en/cloud/latest/rule_engine/rule_engine_save_mysql.html#data-integrations-configuration
done!

2022-11-17 07:34 UTC, closed without merging