EC0-3737 Save device data to AWS RDS for PostgresSQL using the Data Integrations
emqx/cloud-docs pull request #342
Opened 2022-11-20 05:40 UTC by lucas-emqx

2022-11-20 15:20 UTC, zibuyu1995 requested changes

2022-11-20 15:20 UTC, zibuyu1995 commented on en_US/rule_engine/rule_engine_save_rds_mysql.md
> +In this article, we will simulate temperature and humidity data and report these data to EMQX Cloud via the MQTT protocol, and then use the EMQX Cloud Data Integrations to dump the data into PostgreS
It's also

2022-11-20 15:32 UTC, lucas-emqx commented on en_US/rule_engine/rule_engine_save_mysql.md
> +In this article, we will simulate temperature and humidity data and report these data to EMQX Cloud via the MQTT protocol, and then use the EMQX Cloud Data Integrations to dump the data into PostgreS
Thank you, fixed!

2022-11-20 15:32 UTC, lucas-emqx commented on en_US/rule_engine/rule_engine_save_rds_mysql.md
> +In this article, we will simulate temperature and humidity data and report these data to EMQX Cloud via the MQTT protocol, and then use the EMQX Cloud Data Integrations to dump the data into PostgreS
Fixed!

2022-11-21 13:32 UTC, zibuyu1995 requested changes

2022-11-21 13:32 UTC, zibuyu1995 commented on en_US/rule_engine/rule_engine_save_rds_psql
> +    sudo apt-get -y install postgresql
You only need to install the PostgreSQL client
```
sudo apt install -y postgresql-client
```

2022-11-21 15:08 UTC, lucas-emqx commented on en_US/rule_engine/rule_engine_save_rds_psql
> +    sudo apt-get -y install postgresql
Updated as per your request

2022-11-22 02:22 UTC, zibuyu1995 approved these changes

2022-11-22 03:00 UTC, luoyq0629 approved these changes

2022-11-22 21:53 UTC, chenx-work approved these changes

2022-11-24 10:22 UTC, merged