ACL White List  Mode
emqx/cloud-docs pull request #580
Opened 2024-07-05 10:24 UTC by qxyqixin

2024-07-11 01:18 UTC, zibuyu1995 approved these changes

2024-07-11 01:19 UTC, zibuyu1995 requested changes

2024-07-11 01:19 UTC, zibuyu1995 commented on en_US/deployments/acl_dedicated.md
> +- **For Default Access Control**: Click **Authentication & ACL** -> **ACL** in the left menu of the deployment. In the **All Users** tab, add an authorization entry. Enter `#` in the **Topic** field,
是不是不能叫 access control 应该就是 acl 白名单？

2024-07-12 03:00 UTC, luoyq0629 approved these changes

2024-07-15 06:17 UTC, Meggielqk commented on en_US/deployments/acl_dedicated.md
> +- **For Default Access Control**: Click **Authentication & ACL** -> **ACL** in the left menu of the deployment. In the **All Users** tab, add an authorization entry. Enter `#` in the **Topic** field,
Updated to "ACL"

2024-07-15 06:17 UTC, Meggielqk approved these changes

2024-07-16 09:35 UTC, zibuyu1995 approved these changes

2024-07-16 09:35 UTC, merged