TLS version
emqx/cloud-docs pull request #583
Opened 2024-07-11 10:41 UTC by qxyqixin

2024-07-15 02:39 UTC, zibuyu1995 requested changes

2024-07-15 02:39 UTC, zibuyu1995 commented on en_US/create/restriction.md
> +[5] Support TLS 1.2、1.3、1.4.
TLS 没有 1.4 版本

2024-07-15 06:19 UTC, Meggielqk approved these changes

2024-07-16 09:35 UTC, zibuyu1995 approved these changes

2024-07-16 09:35 UTC, merged