feat(docs): add acl_v4 to best_practices
emqx/cloud-docs pull request #608
Opened 2024-08-28 04:06 UTC by luoyq0629

2024-09-02 02:39 UTC, zibuyu1995 requested changes

2024-09-02 02:39 UTC, zibuyu1995 commented on zh_CN/best_practices/acl_v4.md
> +- 内置访问控制的**最大条目数**为部署连接数的两倍。出于性能考虑，若超过此限额，请使用外部 ACL。
这里改一下：出于性能考虑，若超过此限额，请使用外部 ACL。没有性能考虑，就是强限制，上限是 10w。

这里提示再加一行，默认是黑名单

2024-09-02 02:39 UTC, zibuyu1995 commented on zh_CN/best_practices/acl_v4.md
> +在**主题**字段中，您可以使用以下占位符，EMQX Platform 在请求时将自动替换为客户端信息：
这里可以再详细一点，比如几个场景，简单说占位符客户可能不知道什么意思，比如：

如果您想要限制所有用户只允许订阅特定主题，可以类似这样：

用户名 %u，主题 xxx/+/xxx
用户名 %u，主题 xx/%u/report

2024-09-02 05:37 UTC, luoyq0629 commented on zh_CN/best_practices/acl_v4.md
> +- 内置访问控制的**最大条目数**为部署连接数的两倍。出于性能考虑，若超过此限额，请使用外部 ACL。
已修改，黑名单的提示下文有包括。

2024-09-02 05:44 UTC, luoyq0629 commented on zh_CN/best_practices/acl_v4.md
> +在**主题**字段中，您可以使用以下占位符，EMQX Platform 在请求时将自动替换为客户端信息：
已添加

2024-09-04 09:46 UTC, Meggielqk commented on en_US/best_practices/acl_v4.md
> +# Configuring and Using Access Control (ACL) in EMQX Platform v4 Deployments
```suggestion
# Configure and Use Access Control List (ACL) in EMQX Platform v4 Deployments
```

2024-09-04 09:47 UTC, Meggielqk commented on en_US/best_practices/acl_v4.md
> +Access Control (ACL) is used to manage client permissions for PUBLISH and SUBSCRIBE operations within EMQX Platform.
```suggestion
Access Control List (ACL) is used to manage client permissions for PUBLISH and SUBSCRIBE operations within EMQX Platform.
```

2024-09-04 09:47 UTC, Meggielqk commented on en_US/best_practices/acl_v4.md
> +## Adding Access Control Entries
```suggestion
## Add Access Control List Entries
```

2024-09-04 09:47 UTC, Meggielqk commented on en_US/best_practices/acl_v4.md
> +### Bulk Importing Access Control Entries
```suggestion
### Bulk Import ACL Entries
```

2024-09-04 09:48 UTC, Meggielqk commented on en_US/best_practices/acl_v4.md
> +## Using Placeholders
```suggestion
## Use Placeholders
```

2024-09-04 09:48 UTC, Meggielqk commented on en_US/best_practices/acl_v4.md
> +### 1. Not Using External Access Control
```suggestion
### 1. Not Use External Access Control
```

2024-09-04 09:50 UTC, Meggielqk commented on directory.json
> +          "title": "Configuring and Using ACL",
```suggestion
          "title": "Configure and Use ACL",
```

2024-09-05 01:48 UTC, Meggielqk approved these changes

2024-09-11 06:09 UTC, zibuyu1995 approved these changes

2024-09-11 06:09 UTC, merged