feat(docs): add acl_v5 to best_practices
emqx/cloud-docs pull request #609
Opened 2024-08-28 09:26 UTC by luoyq0629

2024-09-02 02:34 UTC, zibuyu1995 requested changes

2024-09-02 02:34 UTC, zibuyu1995 commented on zh_CN/best_practices/acl_v5.md
> +- 内置授权的**最大条目数**为部署连接数的两倍。为确保性能，建议在条目数超过 10 万时使用扩展授权。
这里移除，加上，上限是 10w 连接，英文是 100k。

2024-09-02 05:54 UTC, luoyq0629 commented on zh_CN/best_practices/acl_v5.md
> +- 内置授权的**最大条目数**为部署连接数的两倍。为确保性能，建议在条目数超过 10 万时使用扩展授权。
已处理。

2024-09-05 01:47 UTC, Meggielqk approved these changes

2024-09-11 06:14 UTC, zibuyu1995 approved these changes

2024-09-11 06:20 UTC, merged