fix(docs): fix deployment docs
emqx/cloud-docs pull request #97
Opened 2021-03-31 07:45 UTC by chenx-work

2021-03-31 08:11 UTC, Zhiw commented
1.  不建议一次性提交那么多文件，每完成一个小的任务就可以提交一次
2. 文件夹检查的错误，解决方案参考中文文档的

2021-04-01 01:39 UTC, zibuyu1995 requested changes

2021-04-01 01:39 UTC, zibuyu1995 commented on directory.json
> +              "path": "deployments/Security features and Settings/tls_ssl"
path 一律使用下划线

2021-04-01 01:39 UTC, zibuyu1995 commented on en_US/deployments/Security features and Settings/tls_ssl.md
> +## Generate Self-signed Certificates
Creating a Self-Signed TSL/SSL Certificate

2021-04-01 01:39 UTC, zibuyu1995 commented on en_US/deployments/Security features and Settings/tls_ssl.md
> +### Generation of Server-side Certificate
Creating a Server Certificate

2021-04-01 01:39 UTC, zibuyu1995 commented on en_US/deployments/Security features and Settings/tls_ssl.md
Creating a Client Certificate

2021-04-01 01:39 UTC, zibuyu1995 commented on directory.json
> -        },
MySQL 被删了？

2021-04-01 02:24 UTC, zibuyu1995 requested changes

2021-04-01 08:42 UTC, zibuyu1995 approved these changes

2021-04-01 10:09 UTC, Adek06 approved these changes

2021-04-01 10:09 UTC, merged